### ISSUE TITLE
用这个sink的时候，写数据特别慢

### ISSUE THREAD

**Issue by mdzz9527** [HolyRoy/flume-rabbitMq#1]
1

**Comment by HolyRoy** [comment]
抱歉,我这边好像没有这个问题,具体可以排查一下 看看是sink问题还是channel问题

**Comment by HolyRoy** [comment]
> 只有50/s,

抱歉,我这边好像没有这个问题,具体可以排查一下 看看是sink问题还是channel问题

**Comment by Mr-Malone** [comment]
排查发现数据都堆积在channel中

**Comment by Mr-Malone** [comment]
能加下vx或者QQ交流下吗？
